"""empty message

Revision ID: 32d6efc8ec19
Revises: 36b93d81ad60
Create Date: 2015-02-25 12:47:21.761201

"""

# revision identifiers, used by Alembic.
revision = '32d6efc8ec19'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Brand', sa.String(), nullable=False),
    sa.Column('Time', sa.String(), nullable=False),
    sa.Column('Size', sa.String(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Size', 'loguser', ['Size'], unique=False)
    op.create_index('ix_loguser_Time', 'loguser', ['Time'], unique=False)
    op.create_index('ix_loguser_Type', 'loguser', ['Type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_Type', table_name='loguser')
    op.drop_index('ix_loguser_Time', table_name='loguser')
    op.drop_index('ix_loguser_Size', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
